# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "The Direct Marketer"
description: > # this means to ignore newlines until "email:"
    You need more money coming in. It's not a bad thing to be hungry for a fatter bottom line. In fact, it's your responsibility to yourself and everyone who relies on you to make that margin grow. 


email: james.s.mathison@gmail.com
#blog logo
# logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'James Mathison'
author: 'James Mathison'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.thedirectmarketer.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_DirectMarketer
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+JamesMathison/posts
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/jamesmathison
    desc:	Connect with me on Linkedin
    share_url:
    share_title:
    share_link:
