# Site settings
title: The Direct Marketer
email: james.s.mathison@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/the-direct-marketer" # the subpath of your site, e.g. /blog/
url: "http://www.thedirectmarketer.com" # the base hostname & protocol for your site
twitter_username: _DirectMarketer
github_username:  jamesmathison

# Build settings
markdown: redcarpet #used to be "kramdown"
permalink: /:year-:month-:day/:title.html
exclude: ['REDME.md', 'LICENSE.md']