# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "The Direct Marketer"
description: > # this means to ignore newlines until "email:"
    You need more money coming in. You should be hungry for a fatter bottom line. It's your responsibility to everyone who relies on you to make that margin grow. I can help you with that.


email: james.s.mathison@gmail.com
#blog logo
# logo: "/assets/images/logo.jpg"
# blog cover
cover: "https://s3-eu-west-1.amazonaws.com/the-direct-marketer/Header+Images/typewriter-header.jpg "

name: 'James Mathison'
author: 'James Mathison'
author_image: "/assets/images/author.jpg"

logo: "/assets/images/dm_logo.png"

paginate:	5

url: "http://www.thedirectmarketer.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_DirectMarketer
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+JamesMathison/posts
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/jamesmathison
    desc:	Connect with me on Linkedin
    share_url:
    share_title:
    share_link:
